import Head from 'next/head'
import Image from 'next/image'
import Menu from '../components/Menu/Menu'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LoLo Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Menu/>
    </div>
  )
}
